### ISSUE TITLE
Asks for a valid domain name and gets crashed

### ISSUE THREAD

**Issue by afkcodes** [MSalman5230/Automated_DNS_Updater_Jio_Router#1]
The script fails as its not able to enter valid domain name

![Screenshot from 2024-02-03 11-47-45](https://github.com/MSalman5230/Automated_DNS_Updater_Jio_Router/assets/17390257/164472a9-1db9-4575-b7fa-e79565d34441)

**Comment by MSalman5230** [comment]
Manually enter 
**Domain Name in** 
_Network»LAN»LAN IPv4 Configuration 
Network»LAN»LAN IPv6 Configuration_

You can type anthing, I just put **jio.router**

Its just one time things, as this setting persist after reboot
